name: Build and Push Docker Image to Docker Hub
on:
  [workflow_dispatch]
jobs:
  publish-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build
        run: docker build . -t obrat/fastauth:latest
      - name: push image
        run: docker push obrat/fastauth:latest 